/*
 * The MIT License
 *
 * Copyright (c) 2010 Pablo Fernandez
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.github.scribejava.core.model;

/**
 * represents Authorization Response http://tools.ietf.org/html/rfc6749#section-4.1.2
 *
 * <p>If the resource owner grants the access request, the authorization server issues an
 * authorization code and delivers it to the client by adding the following parameters to the query
 * component of the redirection URI using the "application/x-www-form-urlencoded" format.
 */
public class OAuth2Authorization {

  /**
   * REQUIRED. The authorization code generated by the authorization server. The authorization code
   * MUST expire shortly after it is issued to mitigate the risk of leaks. A maximum authorization
   * code lifetime of 10 minutes is RECOMMENDED. The client MUST NOT use the authorization code more
   * than once. If an authorization code is used more than once, the authorization server MUST deny
   * the request and SHOULD revoke (when possible) all tokens previously issued based on that
   * authorization code. The authorization code is bound to the client identifier and redirection
   * URI.
   */
  private String code;
  /**
   * REQUIRED if the "state" parameter was present in the client authorization request. The exact
   * value received from the client.
   */
  private String state;

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }
}
