name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Stratégie Maven pour mettre à jour les pom.xml
          release-type: maven
          # Branche cible
          target-branch: master

      # Optionnel : Si une release est créée, on peut déclencher le build/deploy
      # Mais votre workflow 'release.yml' actuel s'en chargera car il écoute les tags v*
